# Generated by Django 4.1.2 on 2022-11-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        blank=True, db_column="ID", primary_key=True, serialize=False
                    ),
                ),
                ("year", models.TextField(blank=True, db_column="Year", null=True)),
                (
                    "stationid",
                    models.TextField(blank=True, db_column="StationID", null=True),
                ),
                (
                    "averagemaxtemp",
                    models.FloatField(
                        blank=True, db_column="AverageMaxTemp", null=True
                    ),
                ),
                (
                    "averagemintemp",
                    models.FloatField(
                        blank=True, db_column="AverageMinTemp", null=True
                    ),
                ),
                (
                    "averageprecipitation",
                    models.FloatField(
                        blank=True, db_column="AveragePrecipitation", null=True
                    ),
                ),
            ],
            options={
                "db_table": "result",
            },
        ),
        migrations.CreateModel(
            name="Weather",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        blank=True, db_column="ID", primary_key=True, serialize=False
                    ),
                ),
                ("date", models.TextField(blank=True, db_column="Date", null=True)),
                (
                    "maxtemp",
                    models.FloatField(blank=True, db_column="MaxTemp", null=True),
                ),
                (
                    "mintemp",
                    models.FloatField(blank=True, db_column="MinTemp", null=True),
                ),
                (
                    "precipitation",
                    models.FloatField(blank=True, db_column="Precipitation", null=True),
                ),
                (
                    "stationid",
                    models.TextField(blank=True, db_column="StationID", null=True),
                ),
            ],
            options={
                "db_table": "weather",
            },
        ),
        migrations.CreateModel(
            name="Yield",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        blank=True, db_column="ID", primary_key=True, serialize=False
                    ),
                ),
                ("year", models.IntegerField(blank=True, db_column="Year", null=True)),
                (
                    "totalyield",
                    models.IntegerField(blank=True, db_column="TotalYield", null=True),
                ),
            ],
            options={
                "db_table": "yield",
            },
        ),
    ]
